### ISSUE TITLE
content.opf issues

### ISSUE THREAD

**Issue by acabal** [drgrigg/wilkie-collins_no-name#1]
- `<dc:description>` should be just a one-sentence quick summary, not multiple sentences (I'm putting together a metadata manual right now that will state all of this up front for future reference)
- Missing `<dc:source>` for page scans
- `<manifest>` might be out of order (items should be alphabetized); use the `print-manifest-and-spine` tool to print out a `<manifest>` that you can copy and paste in

**Comment by drgrigg** [comment]
Sorry about the manifest, I was thinking the items had to be in the same order as the ToC.
