### ISSUE TITLE
toc.xhtml issues

### ISSUE THREAD

**Issue by acabal** [drgrigg/wilkie-collins_no-name#4]
- Dedication is missing from ToC
- Remove `<span>`s that have the roman epub type from the parent `<a>` tags. Since the spans are only there to indicate an `epub:type`, you can pull that type up into the parent `<a>` tag and remove the `<span>` entirely. For example `<a href="text/chapter-1-2.xhtml" epub:type="z3998:roman">II</a>`
- Dedication and preface are incorrectly listed as bodymatter in the landmarks

**Comment by drgrigg** [comment]
(1) Should Dedication be in the ToC? It wouldn't be listed on the contents page in a printed book.
(2) Fixed.
(3) Fixed.

**Comment by acabal** [comment]
Dedication should be in the ToC.  Unlike a print book, an ebook ToC is used not only to get an idea of document outline but also to do direct navigation.

**Comment by drgrigg** [comment]
OK, Dedication added to ToC
